### ISSUE TITLE
Make a preloader for the site

### ISSUE THREAD

**Issue by 1poo** [1poo/1poo#2]
This site is kind of clunky and slow so if someone could make a pull request with a preloader, that would be lovely!

**Comment by guilhermeorcezi** [comment]
I will work on this.

**Comment by 1poo** [comment]
Thank you! Please submit a pull request when it is ready, thanks! <3

**Comment by namitdoshi** [comment]
Hey! Would you mind if I work on this too?

**Comment by guilhermeorcezi** [comment]
Done

**Comment by 1poo** [comment]
> Hey! Would you mind if I work on this too?

Sorry, this has already been completed, I will be needing more help with a new project soon, but thanks for the offer.

**Comment by namitdoshi** [comment]
Yeah, let me know about it.
P.S. - Happy to help!
